# try:
#     myFunc()
# except ValueError as e:
#     print(e)

# same handler for multiple exception types
try:
    x is True
except ValueError:
    print(e)
